### ISSUE TITLE
Imagemagick fails to internalize

### ISSUE THREAD

**Issue by tomvanwijk** [bdukes/Chocolatey-Packages#30]
Hello,

All 3 of the imagemagick packages fail to internalize, with the following error:
`` Found internalizable Chocolatey functions. Inspecting values for remote resources.
 Found 'https://imagemagick.org/download/binaries/ImageMagick-7.0.10-6-Q16-x86-dll.exe' for replacement.
 Will use download CDN cache instead of original url.
 Found 'https://imagemagick.org/download/binaries/ImageMagick-7.0.10-6-Q16-x64-dll.exe' for replacement.
 Will use download CDN cache instead of original url.
 Found 'https?://(?:www\.)?imagemagick.org/download/binaries/' for replacement.
 Encountered error downloading package imagemagick.app v:
 System.UriFormatException: Invalid URI: The URI scheme is not valid.
    at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
    at chocolatey.licensed.infrastructure.app.commandresources.RemoteDownloader.get_remote_file_name(String url, String userAgent, String defaultName, PSHost host)
    at chocolatey.licensed.infrastructure.app.commands.ProChocolateyDownloadCommand.process_downloaded_package(IPackage package, String downloadLocation, ChocolateyConfiguration configuration)
    at chocolatey.infrastructure.app.nuget.NugetCommon.<>c__DisplayClass14.<GetPackageManager>b__11(Object s, PackageOperationEventArgs e)
    at NuGet.PackageManager.OnInstalled(PackageOperationEventArgs e)
    at NuGet.PackageManager.Execute(IPackage package, IPackageOperationResolver resolver)
    at NuGet.PackageManager.InstallPackage(IPackage package, Boolean ignoreDependencies, Boolean allowPrereleaseVersions)
    at chocolatey.licensed.infrastructure.app.commands.ProChocolateyDownloadCommand.download_packages(String packageName, String packageVersion, String downloadLocation, ChocolateyConfiguration configuration)``

Is there any way to fix this?

**Comment by Rik-de-Kort** [comment]
Chocolatey appears to be stumbling over the regex used to replace the package url incase get-webheaders fails. Given that the variable being searched over is declared in the same file, I think it would be sufficient to redeclare it instead.

@bdukes does that sound correct? I can submit a PR if necessary.

**Comment by bdukes** [comment]
I've moved the fallback URL generation into `update.ps1`, so that `chocolateyInstall.ps1` only contains full URLs (see 45e91ca).  I've published 7.0.10.7 with that change. Let me know if that fixes the issue for you.  Hope it helps!
